### ISSUE TITLE
add user documentation

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#170]
It is necessary to add user documentation for Kandy, utilizing `Writerside`. To accomplish this, the following steps should be undertaken:

- [x]  add a documentation structure to the project #164 
- [x] Design the home (starting) page #165
- [x] Include an **Overview** section detailing what the library does #166
- [x] Add a section about using the library in `kotlin-notebook` and `jupyter` #167
- [x] Provides a **User Guide** that explains the general principles of working with the library and details the design of the API #168
- [x] Add an **API-Reference** section that lists all the endpoints, methods, or functionalities available
- [x] Add example uses of the library #169
